name: Deploy Components to Testnet
on:
  push:
    branches: [develop]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      cli-version: "0.3.13"
      bw-legacy: false
      deploy-env: "testnet"
      app-name: "devs.near"
      deploy-account-address: builddao.testnet
      signer-account-address: builddao.testnet
      signer-public-key: ed25519:6ycWXZES2zEGPurZqP35AUQx92aAzuS7r9ea1GcSQQiT
    secrets:
      SIGNER_PRIVATE_KEY:  ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }}
