name: Deploy Components to Testnet
on:
  push:
    branches: [develop]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      build-env: "testnet"
      deploy-env: "testnet"
      app-name: "devs.near"
      deploy-account-address: mainnet-on.testnet
      signer-account-address: mainnet-on.testnet
      signer-public-key: ed25519:3qFVXBG21yC3oMeBZNkCRc7d3nUFn7aFbG4BBWciqz6y
    secrets:
      SIGNER_PRIVATE_KEY:  ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }}
